### ISSUE TITLE
Feature request: Horizontal alignment

### ISSUE THREAD

**Issue by cbf305** [nirum/tableprint#16]
This is a simple, lightweight, and awesome package and exactly what I needed to print some database data in my CLI app.  Any chance you could add two parameters for horizontal alignment that takes a string for the alignment of the cell data, such as "left", "center", or "right"?  Something like header_align and row_align??  As it is right now I have to pad all the strings to be the same length as the longest one otherwise the table is difficult to read.

Thanks so much!

**Comment by nirum** [comment]
Great suggestion! Fixed in #17. Functions now take an `align` keyword argument that is either "left", "center" or "right".

For example:
<img width="594" alt="screen shot 2019-02-18 at 5 09 38 pm" src="https://user-images.githubusercontent.com/904854/52983445-06993a80-33a0-11e9-832e-e0ec39957a7e.png">

**Comment by cbf305** [comment]
Awesome, thank you!
